name: sharedtask
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  auth_service:
    path: packages/auth_service
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  cloud_firestore: ^3.1.18
  firebase_auth: ^3.3.20
  firebase_core: ^1.18.0
  equatable: ^2.0.3
  dartz: ^0.10.1
  flutter_native_splash: ^2.2.3+1
  shared_preferences: ^2.0.15

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

